[package]
name = "day03"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.2"
miette = "5.10.0"
nom = "7.1.3"
nom_locate = "4.2.0"

[[bin]]
name = "day03"
path = "main.rs"
